project-includes = [
    ".",
    "backend",
    "ai_engine",
]
search-path = [
    ".",
    "backend",
    "ai_engine",
    "./.venv/Lib/site-packages",
    "c:/Users/godsi/OneDrive/Attachments/Desktop/SIH Project/.venv/Lib/site-packages",
]
infer-with-first-use = false
